name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL to update in config.json'
        required: true

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update config.json with the new URL
        run: |
          CONFIG_FILE="config.json"
          jq --arg url "${{ github.event.inputs.repo_url }}" '.repoPath = $url' "$CONFIG_FILE" > tmp.$$.json && mv tmp.$$.json "$CONFIG_FILE"
          echo "Updated repoPath in config.json to ${{ github.event.inputs.repo_url }}"

      - name: Run JavaScript project
        run: |
          npm install
          npm run start

      - name: Upload Postman Collection
        uses: actions/upload-artifact@v2
        with:
          name: postman-collection
          path: postman_collection.json

      - name: Download Postman Collection Artifact
        uses: actions/download-artifact@v2
        with:
          name: postman-collection
          path: ./

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tantrummaster
          password: dckr_pat_RDR6QwvY94nJ-J2SKyjiPTKnpoU

      - name: Pull the latest ZAP Docker image
        run: docker pull zaproxy/zap-stable

      - name: Check if Postman Collection file exists
        run: ls -l postman_collection.json

      - name: Convert Postman to OpenAPI
        run: |
          npm install postman-to-openapi
          node p2o ./postman_collection.json -f ./openapi.yaml -o ./options.json

      - name: Upload OpenAPI file
        uses: actions/upload-artifact@v2
        with:
          name: openapi-file
          path: openapi.yaml

      - name: Download OpenAPI Artifact
        uses: actions/download-artifact@v2
        with:
          name: openapi-file
          path: ./

      - name: Run ZAP Full Scan
        run: |
          mkdir -p ${{ github.workspace }}/report
          chmod 777 ${{ github.workspace }}/report
          docker run -v ${{ github.workspace }}/report:/zap/wrk:rw -v ${{ github.workspace }}/openapi.yaml:/zap/openapi.yaml:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t https://backend-testing2-0.onrender.com -r /zap/wrk/testreport.html -d /zap/openapi.yaml || true
          echo "Checking if report exists..."
          ls -l ${{ github.workspace }}/report


      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: report/testreport.html
