name: ZAP Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
          tar -xzf ZAP_2.14.0_Linux.tar.gz
          sudo mv ZAP_2.14.0 /opt/zap
          sudo ln -s /opt/zap/zap.sh /usr/local/bin/zap

      - name: Start ZAP
        run: |
          export ZAP_HOME="/home/runner/zap-home"
          mkdir -p $ZAP_HOME
          zap.sh -daemon -port 8080 -host 0.0.0.0 -dir $ZAP_HOME &

      - name: Run API Security Scan
        run: |
          java -jar /opt/zap/ZAP_2.14.0/zap.jar -cmd -quick-scan -t https://backend-testing2-0.onrender.com -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-html-report
          path: zap_report.html
