name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL to update in config.json'
        required: true

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update config.json with the new URL
        run: |
          CONFIG_FILE="config.json"
          jq --arg url "${{ github.event.inputs.repo_url }}" '.repoPath = $url' "$CONFIG_FILE" > tmp.$$.json && mv tmp.$$.json "$CONFIG_FILE"
          echo "Updated repoPath in config.json to ${{ github.event.inputs.repo_url }}"

      - name: Run JavaScript project
        run: |
          npm install
          npm run start

      - name: Upload Postman Collection
        uses: actions/upload-artifact@v2
        with:
          name: postman-collection
          path: postman_collection.json
          
      - name: Download Postman Collection Artifact
        uses: actions/download-artifact@v2
        with:
            name: postman-collection
            path: ./

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tantrummaster
          password: dckr_pat_RDR6QwvY94nJ-J2SKyjiPTKnpoU

      - name: Pull the latest ZAP Docker image
        run: docker pull owasp/zap2docker-stable:latest

      - name: Check if Postman Collection file exists
        run: ls -l postman_collection.json

      - name: Convert Postman to OpenAPI
        run: |
          npm install postman-to-openapi
      - name: conversion
        run: |
          node p2o ./postman_collection.json -f ./openapi.yaml -o ./options.json

      - name: Convert OpenAPI YAML to JSON
        run: |
          python -c "import yaml, json; json.dump(yaml.safe_load(open('openapi.yaml')), open('openapi.json', 'w'), indent=2)"
          
      - name: Upload OpenAPI JSON File
        uses: actions/upload-artifact@v3
        with:
          name: openapi-json
          path: openapi.json

     

      - name: Download OpenAPI JSON Artifact
        uses: actions/download-artifact@v2
        with:
          name: openapi-json
          path: ./

      - name: Run ZAP scan
        run: |
          BASE_URL=$(jq -r '.servers[0].url' openapi.json)
          docker run -v $(pwd):/zap/wrk/:rw --network="host" -t owasp/zap2docker-stable zap-api-scan.py -t openapi.json -f openapi -r zap_report.html -d

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html

