name: ZAP Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
          tar -xzf ZAP_2.14.0_Linux.tar.gz
          sudo mv ZAP_2.14.0 /opt/zap
          sudo ln -s /opt/zap/zap.sh /usr/local/bin/zap

      - name: Start ZAP
        run: |
          export ZAP_HOME="/home/runner/zap-home"
          mkdir -p $ZAP_HOME
          /opt/zap/zap.sh -daemon -port 8080 -host 0.0.0.0 -dir $ZAP_HOME &

      - name: Import OpenAPI and Start Scan
        run: |
          # Wait for ZAP to start
          sleep 30
          
          # Import the OpenAPI file into ZAP
          curl -X POST "http://localhost:8080/JSON/openapi/action/importOpenAPI/?url=https://path/to/OpenAPI.yml"

          # Start the scan
          curl -X POST "http://localhost:8080/JSON/ascan/action/scan/?url=https://backend-testing2-0.onrender.com&recurse=true"

          # Wait for the scan to complete
          sleep 60
          
          # Fetch alerts
          curl "http://localhost:8080/JSON/core/view/alerts/?baseurl=https://backend-testing2-0.onrender.com&count=10"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-html-report
          path: zap_report.html
